version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./projects/project/:/var/www/project:cached
  nginx:
    build: ./docker/nginx
    links:
      - php
    volumes:
      - ./logs/project:/var/log/project:cached